apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: $KUBECONFIG_CERTIFICATE_AUTHORITY_DATA
    server: $KUBECONFIG_SERVER
  name: do-lon1-dialog-bots
contexts:
- context:
    cluster: do-lon1-dialog-bots
    user: do-lon1-dialog-bots-admin
  name: do-lon1-dialog-bots
current-context: do-lon1-dialog-bots
kind: Config
preferences: {}
users:
- name: do-lon1-dialog-bots-admin
  user:
    client-certificate-data: $KUBECONFIG_CLIENT_CERTIFICATE_DATA
    client-key-data: $KUBECONFIG_CLIENT_KEY_DATA
