version: 2
    jobs:
      build:
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Print Dockerfile
              command: echo "FROM python:3.7-alpine

              ENV LIBRARY_PATH=/lib:/usr/lib
              ENV BOT_ENDPOINT=$BOT_ENDPOINT
              ENV BOT_TOKEN=$BOT_TOKEN

              RUN apk add build-base python3-dev py3-pip jpeg-dev zlib-dev libffi-dev libressl-dev
              RUN apk add --no-cache py-cryptography
              RUN python3 -m pip install -r requirements.txt

              WORKDIR "/tmp"
              COPY . /tmp
              CMD ["python3", "src/main.py"]" >> Dockerfile
          - run:
              name: Print credentials
              command: |
                  echo $CREDENTIALS_FILE > credentials.json
                  echo $SETTINGS_FILE > settings.json
          - run:
              name: Build Docker image
              command: docker build -t $IMAGE_NAME:latest .
          - run:
              name: Publish Docker Image to Docker Hub
              command: |
                echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                docker push $IMAGE_NAME:latest
