version: 2
jobs:
    build_docker_image:
        docker:
            - image: circleci/buildpack-deps:stretch
        steps:
            - checkout
            - setup_remote_docker:
                docker_layer_caching: true
            - run:
                name: Print credentials
                command: |
                    echo $CREDENTIALS_FILE > credentials.json
                    echo $SETTINGS_FILE > settings.json
            - run:
                name: Build Docker image
                command: docker build -t $IMAGE_NAME .
            - run:
                name: Publish Docker Image to Docker Hub
                command: |
                    echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
                    docker tag $IMAGE_NAME $COMPANY_NAME/$IMAGE_NAME
                    docker push $COMPANY_NAME/$IMAGE_NAME
    deploy_to_do:
        docker:
            - image: circleci/buildpack-deps:stretch
        steps:
            - checkout
            - setup_remote_docker
            - run:
                name: Install envsubst
                command: |
                    sudo apt-get update && sudo apt-get -y install gettext-base
            - run:
                name: Install kubectl & deploy
                command: |
                    curl -LO https://storage.googleapis.com/kubernetes-release/release/v1.13.5/bin/linux/amd64/kubectl
                    chmod u+x ./kubectl
            - run:
                name: Print kube config
                command: |
                    mkdir -p ~/.kube
                    echo $KUBECONFIG_FILE > ~/.kube/config
            - run:
                name: Make kube deploy config
                command: |
                    envsubst < botconfig.yml
            - run:
                name: Deploy to DigitalOcean
                command: ./kubectl apply -f botconfig.yml
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_docker_image
      - deploy_to_do:
          requires:
            - build_docker_image
          filters:
            branches:
              only: master
